ENV['user_email']='heather.shockney@minedminds.org'
ENV['user_email_pass']='7242316232Hcs'
ENV['dbuser']='Shopping Cart'
ENV['dbpassword']='Min3d~Minds'
ENV['sessionkey']='W00&oofhQDS'
ENV['sessionsecret']='W00f9663!'
ENV['domain']='localhost'
ENV['from']='heather.shockney@minedminds.org'
ENV['a3smtpuser']='AKIAIDZTDHRIWBPZQDOQ'
ENV['a3smtppass']='AjHZL9qFiPrMwAf0G7p63bcjcA4DcyBOekjGYstz491f'
ENV['port']= '5432'
ENV['dbname']='Shopping Cart'
ENV['db']='Shopping Cart.ccar1za80ci4.us-west-2.rds.amazonaws.com'

ENV['email']= 'joseph.mckenzie@minedminds.org'
ENV['email_pass'] ='Bubbadog420'